sailsapp_prod:
  container_name: sailsapp_prod
  build: ./nodejs
  volumes:
    - "../:/server"
    - "/usr/lib/node_modules/sails:/usr/lib/node_modules/sails"
  command: "node app.js --prod"
  ports:
    - "80:1337"
  environment:
    - NODE_ENV=production
  links:
    - mongo:mongo

sailsapp_dev:
  container_name: sailsapp_dev
  build: ./nodejs
  volumes:
    - "../:/server"
    - "/usr/lib/node_modules/sails:/usr/lib/node_modules/sails"
  command: "sails lift"
  ports:
    - "1337:1337"
  links:
    - mongo:mongo

mongo:
  ports:
    - "27017:27017"
  container_name: mongo
  image: mongo
  volumes:
    - "/mongo/db/data:/data/db"
